### ISSUE TITLE
Movements not detected

### ISSUE THREAD

**Issue by sab532** [cornertime/cornertime#1]
I tried on iMac and on PC
Camera allowed but nothing appeard on screen, and no movement detected

**Comment by zoey40105** [comment]
I too experienced this problem. Nothing on screen and no movement is detected. Using Chrome 72.

**Comment by Wyrade** [comment]
Movement works for me on Edge, but not on Firefox or Chrome. I can't set the text-to-speech voice in Edge (haven't tried in the others), and the default there (for me) is horrible.

**Comment by japsu** [comment]
Sorry, seems I was not following the repository and thus didn't get reports of new issues!

Chrome removed some legacy APIs diffy.js was relying on in Spring 2019. I [fixed the app](https://github.com/cornertime/cornertime/commit/b1051949ab411352f94117b7e702919d9695b7fe) in May 2019 and [contributed a fix](https://github.com/maniart/diffyjs/pull/32) back to Diffy.js. I believe the app should now work in most modern browsers. Please reopen if this is still relevant!
