### ISSUE TITLE
Phone/tablet no longer working

### ISSUE THREAD

**Issue by ajjoki** [cornertime/cornertime#12]
Reportedly motion detection no longer works on many smartphones and tablets.

**Comment by japsu** [comment]
Thank you for your report. Cornertime has not been designed with mobile devices in mind and I'm developing and testing it using desktop browsers only.

**Comment by emmatights** [comment]
Was there a resolution to this, it does not work on my iPhone and iPad

**Comment by japsu** [comment]
No, sorry. As stated above, 
>Cornertime has not been designed with mobile devices in mind and I'm developing and testing it using desktop browsers only.
