### ISSUE TITLE
missing modules?

### ISSUE THREAD

**Issue by TheOtherArthur** [cornertime/cornertime#2]
I don't know whether I'm missing something or doing something wrong (possible, I'm new to all this) but I get errors when I try to build the project (using "npm install" in windows. Node.js v12 is installed)

D:\cornertime>npm install
npm WARN tar ENOENT: no such file or directory, open 'D:\cornertime\node_modules\.staging\webpack-dev-server-ef85c1e0\lib\utils\addEntries.js'
npm WARN tar ENOENT: no such file or directory, open 'D:\cornertime\node_modules\.staging\webpack-dev-server-ef85c1e0\lib\utils\colors.js'
npm WARN tar ENOENT: no such file or directory, open 'D:\cornertime\node_modules\.staging\webpack-dev-server-ef85c1e0\lib\utils\createCertificate.js'
npm WARN tar ENOENT: no such file or directory, open 'D:\cornertime\node_modules\.staging\webpack-dev-server-ef85c1e0\lib\utils\createConfig.js'
npm WARN tar ENOENT: no such file or directory, open 'D:\cornertime\node_modules\.staging\webpack-dev-server-ef85c1e0\lib\utils\createDomain.js'
npm WARN tar ENOENT: no such file or directory, open 'D:\cornertime\node_modules\.staging\webpack-dev-server-ef85c1e0\lib\utils\createLogger.js'
npm WARN tar ENOENT: no such file or directory, open 'D:\cornertime\node_modules\.staging\webpack-dev-server-ef85c1e0\lib\utils\defaultTo.js'
npm WARN tar ENOENT: no such file or directory, open 'D:\cornertime\node_modules\.staging\webpack-dev-server-ef85c1e0\lib\utils\getVersions.js'
npm WARN tar ENOENT: no such file or directory, open 'D:\cornertime\node_modules\.staging\webpack-dev-server-ef85c1e0\lib\utils\runBonjour.js'
npm WARN tar ENOENT: no such file or directory, open 'D:\cornertime\node_modules\.staging\webpack-dev-server-ef85c1e0\lib\utils\status.js'
npm WARN tar ENOENT: no such file or directory, lstat 'D:\cornertime\node_modules\.staging\@babel\preset-typescript-aed6ed8d\test\fixtures\jsx-compat\tsx-valid'
npm WARN tar ENOENT: no such file or directory, open 'D:\cornertime\node_modules\.staging\jsdom-5134bf0a\lib\jsdom\living\events\CloseEvent-impl.js'
npm WARN tar ENOENT: no such file or directory, open 'D:\cornertime\node_modules\.staging\jsdom-5134bf0a\lib\jsdom\living\events\CompositionEvent-impl.js'
npm WARN tar ENOENT: no such file or directory, open 'D:\cornertime\node_modules\.staging\jsdom-5134bf0a\lib\jsdom\living\events\CustomEvent-impl.js'
npm WARN tar ENOENT: no such file or directory, open 'D:\cornertime\node_modules\.staging\jsdom-5134bf0a\lib\jsdom\living\events\ErrorEvent-impl.js'
npm WARN tar ENOENT: no such file or directory, open 'D:\cornertime\node_modules\.staging\jsdom-5134bf0a\lib\jsdom\living\events\Event-impl.js'
npm WARN tar ENOENT: no such file or directory, open 'D:\cornertime\node_modules\.staging\jsdom-5134bf0a\lib\jsdom\living\events\EventModifierMixin-impl.js'
npm WARN tar ENOENT: no such file or directory, open 'D:\cornertime\node_modules\.staging\jsdom-5134bf0a\lib\jsdom\living\events\EventTarget-impl.js'
npm WARN tar ENOENT: no such file or directory, open 'D:\cornertime\node_modules\.staging\jsdom-5134bf0a\lib\jsdom\living\events\FocusEvent-impl.js'
npm WARN tar ENOENT: no such file or directory, open 'D:\cornertime\node_modules\.staging\jsdom-5134bf0a\lib\jsdom\living\events\HashChangeEvent-impl.js'
npm WARN tar ENOENT: no such file or directory, open 'D:\cornertime\node_modules\.staging\jsdom-5134bf0a\lib\jsdom\living\events\KeyboardEvent-impl.js'
npm WARN tar ENOENT: no such file or directory, open 'D:\cornertime\node_modules\.staging\jsdom-5134bf0a\lib\jsdom\living\events\MessageEvent-impl.js'
npm WARN tar ENOENT: no such file or directory, open 'D:\cornertime\node_modules\.staging\jsdom-5134bf0a\lib\jsdom\living\events\MouseEvent-impl.js'
npm WARN tar ENOENT: no such file or directory, open 'D:\cornertime\node_modules\.staging\jsdom-5134bf0a\lib\jsdom\living\events\PopStateEvent-impl.js'
npm WARN tar ENOENT: no such file or directory, open 'D:\cornertime\node_modules\.staging\jsdom-5134bf0a\lib\jsdom\living\events\ProgressEvent-impl.js'
npm WARN tar ENOENT: no such file or directory, open 'D:\cornertime\node_modules\.staging\jsdom-5134bf0a\lib\jsdom\living\events\StorageEvent-impl.js'
npm WARN tar ENOENT: no such file or directory, open 'D:\cornertime\node_modules\.staging\jsdom-5134bf0a\lib\jsdom\living\events\TouchEvent-impl.js'
npm WARN tar ENOENT: no such file or directory, open 'D:\cornertime\node_modules\.staging\jsdom-5134bf0a\lib\jsdom\living\events\UIEvent-impl.js'
npm WARN tar ENOENT: no such file or directory, open 'D:\cornertime\node_modules\.staging\jsdom-5134bf0a\lib\jsdom\living\events\WheelEvent-impl.js'
npm WARN cornertime@0.2.0 No repository field.

npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno ENOENT
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t https://github.com/cornertime/diffyjs.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\[redacted]\AppData\Roaming\npm-cache\_logs\2020-02-17T20_39_41_599Z-debug.log

The full log file is attached:
[2020-02-17T20_23_00_620Z-debug.log](https://github.com/cornertime/cornertime/files/4216097/2020-02-17T20_23_00_620Z-debug.log)

Anybody know how to get this built and running?

Edit for redacting my username

**Comment by japsu** [comment]
This is due to the Diffy.js library being depended on using a Git URL instead of a published version in NPM. As you can see in the error message, NPM is trying to invoke the `git` binary, which you don't have installed.

Seems Diffy.js has released a version 1.3.5 containing my fix, so I'll upgrade the dependency to a published version again.

**Comment by japsu** [comment]
@TheOtherArthur Thanks for reporting this. I believe I have fixed it now. Please give it a try and reopen if you still have problems building it :)

**Comment by TheOtherArthur** [comment]
> 
> 
> @TheOtherArthur Thanks for reporting this. I believe I have fixed it now (works on my Windows 10 + Node.js 12). Please give it a try and reopen if you still have problems building it :)

Yes, thank you. It now builds and runs successfully.
