### ISSUE TITLE
Remote view 

### ISSUE THREAD

**Issue by bradlysnyder2021** [cornertime/cornertime#7]
If possible the Webcam feed should be remotely viewable by another person such as a parent who might not be home etc. 

It's great for situations where u can't be in the same place as the person in the corner and need to see what's going on, it also is great for making sure poeple are staying safe distances from each other with covid 19 going on.

**Comment by japsu** [comment]
Thank you for your message. Unfortunately I feel this is somewhat complex to implement (needs servers at least for NAT traversal), privacy sensitive (current implementation sends no information whatsoever over the Internet) and also out of scope with respect to the original vision. Therefore I'm going to close this as "wontfix".

As a workaround, you might be able to use a video conferencing application at the same time as Corner Time.
